### ISSUE TITLE
Do the benchmarks measure the time to transfer the images from the host (CPU) to the GPU and back

### ISSUE THREAD

**Issue by dillonhuff** [TUE-EE-ES/HalideAutoGPU#3]
Hello again! I have a question about what is included in the times reported by the `./run_tests.sh` script. Do the times reported for each version of the application include the time required to transfer the input buffer from host (CPU) memory to device (GPU) memory and then to transfer the resulting output buffer from the device back to the host?

I assume that the times are computed by the benchmark code included with each app (for example):

https://github.com/TUE-EE-ES/HalideAutoGPU/blob/3856605d9d5bcab2a8642628d80fe63894040c6e/TACO_Benchmarks/local_laplacian/process.cpp#L33-L46

But I'm not very familiar with the Halide CUDA runtime, so I could not tell what is actually included in the function calls that are timed in the benchmark.

**Comment by savsiout** [comment]
Hi there,

Halide should only move the inputs once to the GPU then keep them there for follow-up calls to the same pipeline.
The device_sync in the code above forces any functions running on the GPU to finish before taking a measurement, so it takes synchronization costs into account .

In my experience, replacing that with a copy_to_host didn't have much of an impact (as long as device_sync stays there of course).
Removing it altogether may cause the benchmark function to only report the time needed to queue requests to the GPU.

See the definition of benchmark at:

https://github.com/halide/Halide/blob/master/tools/halide_benchmark.h

**Comment by dillonhuff** [comment]
That makes sense. Thanks!
