### ISSUE TITLE
Error when auto-scheduling when using Float(16)

### ISSUE THREAD

**Issue by dillonhuff** [TUE-EE-ES/HalideAutoGPU#7]
@savsiout hello again!

I'm trying to auto-schedule a gaussian pyramid with 16 bit floats as the basic number type instead of 32 bit floats. My current code is here:
https://github.com/dillonhuff/HalideAutoGPU/blob/195ee850bae24ebffdfef3a9828340630f3045db/TACO_Benchmarks/gausspyramid_fp16/gausspyramid_generator.cpp#L23-L32

When I run this code through the auto scheduler it runs and seems to generate code, but when I try to run the generated code on a V100 GPU on AWS I get the following error:

```bash
g++ -Dcuda_alloc -std=c++11 -I ../../distrib/include/ -I ../../distrib/tools/ -I ../support/  -Wall -Werror -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Wno-comment -Wsign-compare -Wno-unknown-warning-option -Wno-psabi  -frtti -I./bin -Wall -O3 process.cpp bin/gausspyramid.a bin/gausspyramid_auto_schedule.a bin/gausspyramid_simple_auto_schedule.a bin/gausspyramid_auto_schedule_store.a bin/gausspyramid_auto_schedule_no_fus.a -o bin/process  -ldl -lpthread -lz -ltinfo -lpng16  -ljpeg -I/usr/include/libpng16 -I/usr/include/libpng16/..   
./bin/process ../images/gray.png 8 1 1 10 ./bin/out.png
Error: CUDA: cuModuleLoadData failed: CUDA_ERROR_INVALID_PTX
Makefile:51: recipe for target 'bin/out.png' failed
make: *** [bin/out.png] Aborted (core dumped)
```

When I use `Float(32)` I do not have this problem. Do you have any idea how I could fix this issue?

Thanks in advance!

**Comment by savsiout** [comment]
This sounds weird indeed. But it doesnt seem to be related to the schedule.
I usually see this when there's a Compute Capability mismatch.
Does it run if you manually schedule the stages on the GPU with gpu_single_thread()?
I'll try to reproduce/debug it when I get some free time :D

**Comment by dillonhuff** [comment]
@savsiout thanks for replying!

I've changed the testbench to only run the manual schedule: https://github.com/dillonhuff/HalideAutoGPU/blob/88c24bd8269047ca25fe856f1517b72f8f3cabe7/TACO_Benchmarks/gausspyramid_fp16/process.cpp#L64

And I have set the manual schedule to compute the downsamples with `gpu_single_thread()` here: 
https://github.com/dillonhuff/HalideAutoGPU/blob/88c24bd8269047ca25fe856f1517b72f8f3cabe7/TACO_Benchmarks/gausspyramid_fp16/gausspyramid_generator.cpp#L69-L72

When I use these settings the code runs and I get the following output:

```bash
g++ -Dcuda_alloc -std=c++11 -I ../../distrib/include/ -I ../../distrib/tools/ -I ../support/  -Wall -Werror -Wno-unused-function -Wcast-qual -Wignored-qualifiers -Wno-comment -Wsign-compare -Wno-unknown-warning-option -Wno-psabi  -frtti -I./bin -Wall -O3 process.cpp bin/gausspyramid.a bin/gausspyramid_auto_schedule.a bin/gausspyramid_simple_auto_schedule.a bin/gausspyramid_auto_schedule_store.a bin/gausspyramid_auto_schedule_no_fus.a -o bin/process  -ldl -lpthread -lz -ltinfo -lpng16  -ljpeg -I/usr/include/libpng16 -I/usr/include/libpng16/..   
./bin/process ../images/gray.png 8 1 1 10 ./bin/out.png
Manual time: 186.207ms
Done, transferring image
./bin/process ../images/gray.png 8 1 1 10 ./bin/out.tiff
Manual time: 186.212ms
Done, transferring image
```
